#!/usr/bin/env ruby

require 'optparse'

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: setup [options]"

  opts.on("-v", "--[no-]verbose", "Run verbosely") do |v|
    options[:verbose] = v
  end

  opts.on("-d", "--dry-run", "Run but do not create symlinks (implies verbosity)") do |d|
    options[:verbose] = d
    options[:dry_run] = d
  end
end.parse!

IGNORED_DIRS = %w{.git/ .git}
IGNORED_FILES = %w{setup Brewfile}

Dir.glob("**/*", File::FNM_DOTMATCH) do |file|
  next if File.directory?(file) || file.start_with?(*IGNORED_DIRS) || IGNORED_FILES.include?(file)

  full_path = File.join(__dir__, file)
  new_path = File.join(ENV['HOME'], file)
  new_dir = File.dirname(new_path)

  if options[:verbose]
    puts "#{full_path} -> #{new_dir}"
  end

  unless options[:dry_run]
    %x(mkdir -p #{new_dir} && ln -nfs #{full_path} #{new_dir})
  end
end

puts <<~STR
Remaining setup:
* `brew bundle` in this directory to install homebrew packages
STR
